name: 3. CD - Deploy para Produção

on:
  push:
    branches:
      - master

env:
  ECS_CLUSTER_NAME: chat-edu-assistant-cluster
  ECS_SERVICE_NAME: chat-assistant-service
  ECS_TASK_DEFINITION: task-definition.json
  ECS_CONTAINER_NAME: chat-assistant-container

jobs:
  build_push_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir Variáveis de Imagem e Tags
        id: vars
        run: |
          REPOSITORY=${{ secrets.ECR_REPOSITORY }}

          IMAGE_SHA_TAG=${{ github.sha }}

          ECR_URI_SHA=${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:$IMAGE_SHA_TAG
          echo "ECR_URI_SHA=$ECR_URI_SHA" >> $GITHUB_OUTPUT

          ECR_URI_LATEST=${{ steps.login-ecr.outputs.registry }}/$REPOSITORY:latest
          echo "ECR_URI_LATEST=$ECR_URI_LATEST" >> $GITHUB_OUTPUT

      - name: Build e Push da Imagem
        env:
          ECR_URI_SHA: ${{ steps.vars.outputs.ECR_URI_SHA }}
          ECR_URI_LATEST: ${{ steps.vars.outputs.ECR_URI_LATEST }}
        run: |
          docker build -t $ECR_URI_SHA -t $ECR_URI_LATEST .
          docker push $ECR_URI_SHA
          docker push $ECR_URI_LATEST

      - name: Renderizar Nova Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ steps.vars.outputs.ECR_URI_SHA }}

      - name: Deploy no Serviço ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
